-- Migration: Create admin_notifications table
-- Run this in your Supabase/Postgres console
-- This table stores admin-focused notifications, includes the actor (admin) who triggered the event

DROP TABLE IF EXISTS admin_notifications;

CREATE TABLE admin_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id UUID NOT NULL REFERENCES users(id), -- the admin who performed the action
    user_id UUID, -- the user affected by the action (may be null for system events)
    notification_id BIGINT REFERENCES notifications(id), -- optional link to the user-facing notification
    -- Use UUID for report_id so it matches the `reports.id` type (this project uses UUIDs for reports)
    report_id UUID,
    title TEXT,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexes to speed up admin queries
CREATE INDEX idx_admin_notifications_actor_id ON admin_notifications(actor_id);
CREATE INDEX idx_admin_notifications_user_id ON admin_notifications(user_id);
CREATE INDEX idx_admin_notifications_created_at ON admin_notifications(created_at DESC);

-- NOTE:
-- If you already applied the previous version of this migration (report_id as BIGINT) to a live DB,
-- adjust the column type in your Supabase SQL console rather than re-running the CREATE above.
-- Suggested ALTER approach (safe when existing values are UUID strings stored as text or when there
-- are no conflicting numeric values):
--
-- ALTER TABLE admin_notifications DROP COLUMN IF EXISTS report_id;
-- ALTER TABLE admin_notifications ADD COLUMN report_id UUID;
-- ALTER TABLE admin_notifications
--   ADD CONSTRAINT fk_admin_notifications_report
--   FOREIGN KEY (report_id) REFERENCES reports(id);

-- If your `notifications` table also used BIGINT for report_id (mismatch), consider updating it similarly:
-- ALTER TABLE notifications DROP COLUMN IF EXISTS report_id;
-- ALTER TABLE notifications ADD COLUMN report_id UUID;
-- ALTER TABLE notifications
--   ADD CONSTRAINT fk_notifications_report
--   FOREIGN KEY (report_id) REFERENCES reports(id);
