-- Migration 010: Create PostGIS Safezones and Hotspots Tables
-- Purpose: Support responder map functionality with safezone creation and hotspot clustering

-- ============================================================================
-- 1. Enable PostGIS Extension (if not already enabled)
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_raster;

-- ============================================================================
-- 2. Create Safezones Table
-- Purpose: Store user-created safety zones on the responder map
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.safezones (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    center JSONB NOT NULL DEFAULT '{}', -- Format: {"latitude": number, "longitude": number}
    radius_meters INTEGER NOT NULL DEFAULT 100, -- Radius in meters (10-1000)
    geom GEOGRAPHY(POINT, 4326), -- PostGIS geometry for spatial queries
    is_active BOOLEAN DEFAULT true,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for safezones
CREATE INDEX idx_safezones_is_active ON public.safezones(is_active);
CREATE INDEX idx_safezones_created_by ON public.safezones(created_by);
CREATE INDEX idx_safezones_geom ON public.safezones USING GIST(geom);

-- ============================================================================
-- 3. Create Hotspots Table
-- Purpose: Store automatically generated incident clusters (auto-generated by PostGIS)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.hotspots (
    id BIGSERIAL PRIMARY KEY,
    centroid JSONB NOT NULL DEFAULT '{}', -- Format: {"latitude": number, "longitude": number}
    geom GEOGRAPHY(POINT, 4326), -- PostGIS geometry for spatial queries
    report_count INTEGER DEFAULT 0, -- Number of reports in this cluster
    category_counts JSONB DEFAULT '{}', -- Format: {"Crime": 5, "Accident": 3, ...}
    first_report_at TIMESTAMP WITH TIME ZONE,
    last_report_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for hotspots
CREATE INDEX idx_hotspots_report_count ON public.hotspots(report_count DESC);
CREATE INDEX idx_hotspots_geom ON public.hotspots USING GIST(geom);
CREATE INDEX idx_hotspots_created_at ON public.hotspots(created_at DESC);

-- ============================================================================
-- 4. Add geom Column to Reports (if not exists)
-- Purpose: Store report locations for PostGIS clustering
-- ============================================================================
ALTER TABLE public.reports 
ADD COLUMN IF NOT EXISTS geom GEOGRAPHY(POINT, 4326);

-- Create index for reports geom
CREATE INDEX IF NOT EXISTS idx_reports_geom ON public.reports USING GIST(geom);

-- ============================================================================
-- 5. Create RPC Function: refresh_hotspots_dbscan
-- Purpose: Automatically generate hotspots from report clusters using DBSCAN algorithm
-- This function should be called periodically or on-demand by the backend
-- ============================================================================
CREATE OR REPLACE FUNCTION public.refresh_hotspots_dbscan(
    min_cluster_size INTEGER DEFAULT 3,
    distance_meters INTEGER DEFAULT 500
)
RETURNS TABLE (
    success BOOLEAN,
    message TEXT,
    hotspots_count INTEGER
) AS $$
DECLARE
    v_hotspots_count INTEGER := 0;
BEGIN
    -- Clear existing hotspots
    DELETE FROM public.hotspots;
    
    -- Insert new hotspots using ST_ClusterDBSCAN
    -- ST_ClusterDBSCAN groups nearby reports into clusters based on distance
    INSERT INTO public.hotspots (centroid, geom, report_count, category_counts, first_report_at, last_report_at)
    SELECT
        ST_AsGeoJSON(ST_Centroid(ST_Collect(r.geom)))::JSONB AS centroid,
        ST_Centroid(ST_Collect(r.geom)) AS geom,
        COUNT(*)::INTEGER AS report_count,
        -- Count reports by category
        jsonb_object_agg(
            COALESCE(r.category, 'Uncategorized'),
            COUNT(*)
        ) AS category_counts,
        MIN(r.created_at) AS first_report_at,
        MAX(r.created_at) AS last_report_at
    FROM public.reports r
    WHERE 
        r.deleted_at IS NULL
        AND r.geom IS NOT NULL
        AND ST_ClusterDBSCAN(r.geom, distance_meters, min_cluster_size) OVER (ORDER BY r.id) IS NOT NULL
    GROUP BY ST_ClusterDBSCAN(r.geom, distance_meters, min_cluster_size) OVER (ORDER BY r.id)
    HAVING COUNT(*) >= min_cluster_size;
    
    -- Get count of created hotspots
    SELECT COUNT(*) INTO v_hotspots_count FROM public.hotspots;
    
    RETURN QUERY SELECT 
        true,
        'Hotspots refreshed successfully. ' || v_hotspots_count || ' hotspots created.',
        v_hotspots_count;
        
EXCEPTION WHEN OTHERS THEN
    RETURN QUERY SELECT 
        false,
        'Error refreshing hotspots: ' || SQLERRM,
        0;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 6. Create Trigger to Update Safezones updated_at
-- ============================================================================
CREATE OR REPLACE FUNCTION public.update_safezones_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF NOT EXISTS safezones_updated_at_trigger ON public.safezones;
CREATE TRIGGER safezones_updated_at_trigger
BEFORE UPDATE ON public.safezones
FOR EACH ROW
EXECUTE FUNCTION public.update_safezones_updated_at();

-- ============================================================================
-- 7. Create Trigger to Update Hotspots updated_at
-- ============================================================================
CREATE OR REPLACE FUNCTION public.update_hotspots_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF NOT EXISTS hotspots_updated_at_trigger ON public.hotspots;
CREATE TRIGGER hotspots_updated_at_trigger
BEFORE UPDATE ON public.hotspots
FOR EACH ROW
EXECUTE FUNCTION public.update_hotspots_updated_at();

-- ============================================================================
-- 8. Helper Function: Update Report Geom from Lat/Lng
-- Purpose: Automatically populate geom column when latitude/longitude are set
-- ============================================================================
CREATE OR REPLACE FUNCTION public.update_report_geom()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
        NEW.geom = ST_Point(NEW.longitude, NEW.latitude)::GEOGRAPHY;
    ELSE
        NEW.geom = NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF NOT EXISTS report_geom_update_trigger ON public.reports;
CREATE TRIGGER report_geom_update_trigger
BEFORE INSERT OR UPDATE ON public.reports
FOR EACH ROW
EXECUTE FUNCTION public.update_report_geom();

-- ============================================================================
-- 9. Populate Existing Reports with Geom
-- Purpose: Initialize geom column for reports that already exist
-- ============================================================================
UPDATE public.reports
SET geom = ST_Point(longitude, latitude)::GEOGRAPHY
WHERE latitude IS NOT NULL 
  AND longitude IS NOT NULL 
  AND geom IS NULL;

-- ============================================================================
-- 10. Initial Hotspot Generation
-- Purpose: Generate initial hotspots from existing reports
-- ============================================================================
SELECT public.refresh_hotspots_dbscan(3, 500);

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Tables created:
-- - safezones: User-created safety zones
-- - hotspots: Auto-generated incident clusters
-- 
-- Functions created:
-- - refresh_hotspots_dbscan(): Regenerate hotspots from reports
-- 
-- Triggers created:
-- - update_safezones_updated_at: Auto-update timestamp on safezone changes
-- - update_hotspots_updated_at: Auto-update timestamp on hotspot changes
-- - report_geom_update_trigger: Auto-populate geom from lat/lng
-- 
-- Backend routes to support these tables:
-- - GET /api/safezones: Fetch all active safezones
-- - POST /api/safezones: Create new safezone
-- - PUT /api/safezones/<id>: Update safezone
-- - DELETE /api/safezones/<id>: Delete safezone
-- - GET /api/hotspots: Fetch all hotspots
-- - POST /api/hotspots/refresh: Manually refresh hotspots
